### ISSUE TITLE
tcp connection not authed

### ISSUE THREAD

**Issue by muggle0** [tencentyun/cmq-java-tcp-sdk#14]
我在我的代码中构建了一个单例的 producer并能正常发送消息，但当运行一段时间之后在发送消息会出现 认证失败的情况：
code:306 error:tcp connection not authed

当重新new 一个单例再次尝试发送消息也可能会出现上述的情况。
其中间隔时间不定

**Comment by yorkhellen** [comment]
https://github.com/tencentyun/cmq-java-tcp-sdk/pull/17
